### ISSUE TITLE
Module Error when installed nexmo using ubunutu terminal

### ISSUE THREAD

**Issue by ankushbadlas** [thibault/django-nexmo#5]
Hello Sir,

I am getting the module import error when I installed django-nexmo module in my python django application. Please see attached screenshot. I am using the following versions:

Python: 3.5.2
Django: 1.11.2
ubuntu : 16.04

I installed the django-naxmo app using the following link instructions:
https://pypi.python.org/pypi/django-nexmo
https://github.com/thibault/django-nexmo

Please help me how I resolve this error message and need ti run python shelll command.

https://user-images.githubusercontent.com/7335485/35508346-0f903f76-0516-11e8-8cea-0e32e7af4dd1.png

**Comment by thibault** [comment]
There was an error in the installation instructions, fixed in #2. Could you please read the new instructions and try again?

**Comment by thibault** [comment]
I'm marking this as fixed, feel free to reopen if you still have the problem.

**Comment by ankushbadlas** [comment]
same problem after mentioned following details in setting.py
INSTALLED_APPS = [
    'djexmo',
]


# Nexmo Message Setting APIs 
NEXMO_API_KEY = '78******'
NEXMO_API_SECRET = '4d********'
NEXMO_DEFAULT_FROM = '1**********'

Please help me that I did the configuration in right direction. Looking forward to hear you soon.

Thanks

**Comment by ankushbadlas** [comment]
I am getting the same issue again. Please help me to solve this nexmo task
issue.

**Comment by thibault** [comment]
@ankushbadlas Did you follow the updated installation instructions? Please, paste the result of the command `pip freeze`.

Also, you listed your api key and api secret in the screen capture you posted. I removed it, but you should generate a new token right now.
